# Generated by Django 2.0.12 on 2021-05-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'medical record', 'verbose_name_plural': 'medical record'},
        ),
        migrations.AlterModelOptions(
            name='chain',
            options={'verbose_name': 'patient', 'verbose_name_plural': 'patient'},
        ),
        migrations.RenameField(
            model_name='block',
            old_name='chain',
            new_name='Patient',
        ),
    ]
